# Welcome to Jekyll!

# Website settings
title: "Mustaqim Malim"
description: "Mustaqim's blog."
keywords: "Mustaqim,Malim,computer,Science,code,programming,tech,security,windows,linux,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: "https://www.mustaqim.me"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Mustaqim'
  first_name: 'Mustaqim'
  last_name: 'Malim'
  email: 'mustaqim@protonmail.com'
  twitter_username: 'mustaqim'
  github_username: 'malimM'
  head_img: 'static/img/landing/MM.jpg'
  desc: 'I am a Computer Science student.'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

  - id: 'links'
    i18n: 'nav.link'
    name: 'Links'
    tpl: 'links.html'
    css: 'contact'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/South-Africa.png'

# blog img path
img_path: 'https://www.mustaqim.me/static/img/blog'

# donate
donate:
  bitcoin: 'static/img/pay/bitcoin.png'
  paypal: 'static/img/pay/paypal.png'

# comment
disqus:
  name: malimM
  public_key: vvgx24XOHocrQL2G3FxemInmggUUpwTTjzfiYe8wv28pkIcwzK33CnjlyRBEuDMf

# google analytics
ga:
  id: UA-70999622-1

# Build settings
encoding: "utf-8"

# other settings
gems:
  - jekyll-sitemap
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
